name: "Build docker"

on:
  pull_request:

  push:
    paths-ignore:
      - '**.md'

permissions: read-all

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: setup-go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: 'go.mod'

    - name: Enable docker experimental
      run: |
        echo $'{"experimental": true}' | sudo dd status=none of=/etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: build_docker
      run: make build
